[functions.publish-to-social]
enabled = true
verify_jwt = true
entrypoint = "./functions/publish-to-social/index.ts"

[functions.linkedin-auth-callback]
verify_jwt = false

[functions.twitter-auth-callback]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.cancel-delete-user]
verify_jwt = false

[functions.hard-delete-users]
verify_jwt = false

[functions.instagram-auth-callback]
verify_jwt = false

[functions.instagram-auth-start]
verify_jwt = true

[functions.threads-auth-start]
verify_jwt = true

[functions.threads-auth-callback]
verify_jwt = false

[functions.facebook-auth-callback]
verify_jwt = false

[functions.storage-cleanup]
enabled = true
verify_jwt = false
import_map = "./functions/_shared/import_map.json"
entrypoint = "./functions/storage-cleanup/index.ts"

[functions.create-payment-intent]
enabled = true
verify_jwt = true
import_map = "./functions/_shared/import_map.json"
entrypoint = "./functions/create-payment-intent/index.ts"

[functions.link-referral]
  verify_jwt = false


[functions.stripe-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/_shared/import_map.json"
entrypoint = "./functions/stripe-webhook/index.ts"

[functions.meta-review-caller]
verify_jwt = false


[functions.get-subscription-details]
enabled = true
verify_jwt = true
import_map = "./functions/get-subscription-details/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-subscription-details/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-subscription-details/*.html" ]

[functions.delete-app-connection]
verify_jwt = true

[functions.set-password-flag]
verify_jwt = true

[functions.signup-validation]
verify_jwt = false

[functions.subscribe-newsletter]
enabled = true
verify_jwt = false
import_map = "./functions/subscribe-newsletter/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/subscribe-newsletter/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/subscribe-newsletter/*.html" ]

[functions.email-worker]
enabled = true
verify_jwt = false
import_map = "./functions/email-worker/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/email-worker/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/email-worker/*.html" ]

[functions.confirm-newsletter-subscription]
enabled = true
verify_jwt = false
import_map = "./functions/confirm-newsletter-subscription/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/confirm-newsletter-subscription/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/confirm-newsletter-subscription/*.html" ]

[functions.warriorplus-postback-handler]
verify_jwt = false
