-- Table to store state and code verifier for OAuth 2.0 flows
CREATE TABLE public.oauth_state (
    id bigint NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at timestamptz NOT NULL DEFAULT now(),
    state text NOT NULL UNIQUE,
    code_verifier text NOT NULL,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Enable Row Level Security
ALTER TABLE public.oauth_state ENABLE ROW LEVEL SECURITY;

-- Add comments to the table and columns
COMMENT ON TABLE public.oauth_state IS 'Stores state and code verifier for OAuth 2.0 authorization flows to prevent CSRF attacks and manage PKCE.';
COMMENT ON COLUMN public.oauth_state.state IS 'A random string generated by the application to maintain state between the request and callback.';
COMMENT ON COLUMN public.oauth_state.code_verifier IS 'The PKCE code verifier.';
COMMENT ON COLUMN public.oauth_state.user_id IS 'The user who initiated the OAuth flow.';
