-- 1. Enable the pgmq extension for message queuing
CREATE EXTENSION IF NOT EXISTS pgmq CASCADE;

-- 2. Create the queue for handling email sending
SELECT pgmq.create('email_queue');

-- 3. Create the table to store newsletter subscribers
CREATE TABLE public.newsletter_subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- Use SET NULL to keep email even if user is deleted
    email TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'pending', -- e.g., pending, subscribed, unsubscribed
    subscribed_at TIMESTAMPTZ,
    unsubscribed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add comments for clarity
COMMENT ON COLUMN public.newsletter_subscribers.status IS 'The subscription status, e.g., pending, subscribed, unsubscribed.';
COMMENT ON COLUMN public.newsletter_subscribers.user_id IS 'Link to the user profile if the subscriber is also a registered user.';


-- 4. Enable Row Level Security on the table
ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;


-- 5. Create RLS policies
-- Allow public read access 
CREATE POLICY "Public subscriber info is viewable by everyone."
ON public.newsletter_subscribers FOR SELECT
USING ( true );

-- Allow anyone (including anonymous users from the signup form) to insert a new subscriber entry
CREATE POLICY "Anyone can sign up for the newsletter."
ON public.newsletter_subscribers FOR INSERT
WITH CHECK ( true );

-- Allow users to update their own subscription status (e.g., unsubscribe)
CREATE POLICY "Users can update their own subscription."
ON public.newsletter_subscribers FOR UPDATE
USING ( auth.uid() = user_id );

-- Allow users to delete their own subscription
CREATE POLICY "Users can delete their own subscription."
ON public.newsletter_subscribers FOR DELETE
USING ( auth.uid() = user_id );
