-- Create the table for storing generated posts
create table public.generated_posts (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    source_url text,
    language text,
    content text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add comments to the table and columns
comment on table public.generated_posts is 'Stores the AI-generated content for each user.';
comment on column public.generated_posts.user_id is 'The user who generated the post.';
comment on column public.generated_posts.source_url is 'The original URL of the article.';
comment on column public.generated_posts.language is 'The target language for the generated content.';
comment on column public.generated_posts.content is 'The AI-generated post content.';

-- Enable Row Level Security (RLS)
alter table public.generated_posts enable row level security;

-- Create a policy that allows users to see only their own posts
create policy "Users can view their own generated posts"
on public.generated_posts for select
using (auth.uid() = user_id);

-- Create a policy that allows users to insert their own posts
create policy "Users can insert their own generated posts"
on public.generated_posts for insert
with check (auth.uid() = user_id);
