-- Tabela para armazenar prompts customizados dos usuários
create table public.user_prompts (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    name text not null check (char_length(name) <= 100),
    text text not null check (char_length(text) <= 5000),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Comentários para clareza
comment on table public.user_prompts is 'Stores custom prompts created by users.';
comment on column public.user_prompts.name is 'The user-given name for the prompt.';
comment on column public.user_prompts.text is 'The content of the custom prompt.';

-- Habilitar Row Level Security (RLS)
alter table public.user_prompts enable row level security;

-- Políticas de RLS
create policy "Users can view their own prompts" on public.user_prompts for select using (auth.uid() = user_id);
create policy "Users can insert their own prompts" on public.user_prompts for insert with check (auth.uid() = user_id);
create policy "Users can update their own prompts" on public.user_prompts for update using (auth.uid() = user_id);
create policy "Users can delete their own prompts" on public.user_prompts for delete using (auth.uid() = user_id);

-- Adicionar índice no user_id para otimizar buscas
create index ix_user_prompts_user_id on public.user_prompts (user_id);

-- Função de gatilho para verificar o limite de prompts
create or replace function public.check_prompt_limit()
returns trigger as $FUNCTION$
begin
  if (select count(*) from public.user_prompts where user_id = NEW.user_id) >= 5 then
    raise exception 'User has reached the prompt limit of 5.';
  end if;
  return NEW;
end;
$FUNCTION$ language plpgsql;

-- Gatilho que chama a função antes de uma inserção
create trigger enforce_prompt_limit_before_insert
before insert on public.user_prompts
for each row execute procedure public.check_prompt_limit();
